/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrencyResponse
 */
export interface CurrencyResponse {
    /**
     * 
     * @type {string}
     * @memberof CurrencyResponse
     */
    iso3: string;
    /**
     * 
     * @type {number}
     * @memberof CurrencyResponse
     */
    decimals?: number;
}

/**
 * Check if a given object implements the CurrencyResponse interface.
 */
export function instanceOfCurrencyResponse(value: object): value is CurrencyResponse {
    if (!('iso3' in value) || value['iso3'] === undefined) return false;
    return true;
}

export function CurrencyResponseFromJSON(json: any): CurrencyResponse {
    return CurrencyResponseFromJSONTyped(json, false);
}

export function CurrencyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'iso3': json['iso3'],
        'decimals': json['decimals'] == null ? undefined : json['decimals'],
    };
}

export function CurrencyResponseToJSON(json: any): CurrencyResponse {
    return CurrencyResponseToJSONTyped(json, false);
}

export function CurrencyResponseToJSONTyped(value?: CurrencyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iso3': value['iso3'],
        'decimals': value['decimals'],
    };
}

