/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountCreationRequest
 */
export interface AccountCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountCreationRequest
     */
    iban: string;
    /**
     * 
     * @type {string}
     * @memberof AccountCreationRequest
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof AccountCreationRequest
     */
    currency: string;
}

/**
 * Check if a given object implements the AccountCreationRequest interface.
 */
export function instanceOfAccountCreationRequest(value: object): value is AccountCreationRequest {
    if (!('iban' in value) || value['iban'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function AccountCreationRequestFromJSON(json: any): AccountCreationRequest {
    return AccountCreationRequestFromJSONTyped(json, false);
}

export function AccountCreationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCreationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iban': json['iban'],
        'customerId': json['customerId'],
        'currency': json['currency'],
    };
}

export function AccountCreationRequestToJSON(json: any): AccountCreationRequest {
    return AccountCreationRequestToJSONTyped(json, false);
}

export function AccountCreationRequestToJSONTyped(value?: AccountCreationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iban': value['iban'],
        'customerId': value['customerId'],
        'currency': value['currency'],
    };
}

