/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountResponse
 */
export interface AccountResponse {
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    iban: string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof AccountResponse
     */
    balance: number;
}

/**
 * Check if a given object implements the AccountResponse interface.
 */
export function instanceOfAccountResponse(value: object): value is AccountResponse {
    if (!('iban' in value) || value['iban'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    return true;
}

export function AccountResponseFromJSON(json: any): AccountResponse {
    return AccountResponseFromJSONTyped(json, false);
}

export function AccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'iban': json['iban'],
        'customerId': json['customerId'],
        'currency': json['currency'],
        'balance': json['balance'],
    };
}

export function AccountResponseToJSON(json: any): AccountResponse {
    return AccountResponseToJSONTyped(json, false);
}

export function AccountResponseToJSONTyped(value?: AccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iban': value['iban'],
        'customerId': value['customerId'],
        'currency': value['currency'],
        'balance': value['balance'],
    };
}

