/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoneyTransferRequest
 */
export interface MoneyTransferRequest {
    /**
     * 
     * @type {string}
     * @memberof MoneyTransferRequest
     */
    sourceIban: string;
    /**
     * 
     * @type {string}
     * @memberof MoneyTransferRequest
     */
    destinationIban: string;
    /**
     * 
     * @type {number}
     * @memberof MoneyTransferRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof MoneyTransferRequest
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof MoneyTransferRequest
     */
    label: string;
}

/**
 * Check if a given object implements the MoneyTransferRequest interface.
 */
export function instanceOfMoneyTransferRequest(value: object): value is MoneyTransferRequest {
    if (!('sourceIban' in value) || value['sourceIban'] === undefined) return false;
    if (!('destinationIban' in value) || value['destinationIban'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function MoneyTransferRequestFromJSON(json: any): MoneyTransferRequest {
    return MoneyTransferRequestFromJSONTyped(json, false);
}

export function MoneyTransferRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoneyTransferRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceIban': json['sourceIban'],
        'destinationIban': json['destinationIban'],
        'amount': json['amount'],
        'currency': json['currency'],
        'label': json['label'],
    };
}

export function MoneyTransferRequestToJSON(json: any): MoneyTransferRequest {
    return MoneyTransferRequestToJSONTyped(json, false);
}

export function MoneyTransferRequestToJSONTyped(value?: MoneyTransferRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceIban': value['sourceIban'],
        'destinationIban': value['destinationIban'],
        'amount': value['amount'],
        'currency': value['currency'],
        'label': value['label'],
    };
}

