/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoneyTransferResponse
 */
export interface MoneyTransferResponse {
    /**
     * 
     * @type {string}
     * @memberof MoneyTransferResponse
     */
    sourceIban?: string;
    /**
     * 
     * @type {string}
     * @memberof MoneyTransferResponse
     */
    destinationIban?: string;
    /**
     * In minor unit (i.e. 1000 for 1000 XPF, 10.00 USD, 1.000 KWD)
     * @type {number}
     * @memberof MoneyTransferResponse
     */
    amount?: number;
    /**
     * in ISO_3 format
     * @type {string}
     * @memberof MoneyTransferResponse
     */
    currency?: string;
    /**
     * 
     * @type {Date}
     * @memberof MoneyTransferResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof MoneyTransferResponse
     */
    label?: string;
}

/**
 * Check if a given object implements the MoneyTransferResponse interface.
 */
export function instanceOfMoneyTransferResponse(value: object): value is MoneyTransferResponse {
    return true;
}

export function MoneyTransferResponseFromJSON(json: any): MoneyTransferResponse {
    return MoneyTransferResponseFromJSONTyped(json, false);
}

export function MoneyTransferResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoneyTransferResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceIban': json['sourceIban'] == null ? undefined : json['sourceIban'],
        'destinationIban': json['destinationIban'] == null ? undefined : json['destinationIban'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'label': json['label'] == null ? undefined : json['label'],
    };
}

export function MoneyTransferResponseToJSON(json: any): MoneyTransferResponse {
    return MoneyTransferResponseToJSONTyped(json, false);
}

export function MoneyTransferResponseToJSONTyped(value?: MoneyTransferResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceIban': value['sourceIban'],
        'destinationIban': value['destinationIban'],
        'amount': value['amount'],
        'currency': value['currency'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'label': value['label'],
    };
}

