/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { MoneyTransferResponse } from './MoneyTransferResponse';
import {
    MoneyTransferResponseFromJSON,
    MoneyTransferResponseFromJSONTyped,
    MoneyTransferResponseToJSON,
    MoneyTransferResponseToJSONTyped,
} from './MoneyTransferResponse';

/**
 * 
 * @export
 * @interface PagedModelMoneyTransferResponse
 */
export interface PagedModelMoneyTransferResponse {
    /**
     * 
     * @type {Array<MoneyTransferResponse>}
     * @memberof PagedModelMoneyTransferResponse
     */
    content?: Array<MoneyTransferResponse>;
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelMoneyTransferResponse
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelMoneyTransferResponse interface.
 */
export function instanceOfPagedModelMoneyTransferResponse(value: object): value is PagedModelMoneyTransferResponse {
    return true;
}

export function PagedModelMoneyTransferResponseFromJSON(json: any): PagedModelMoneyTransferResponse {
    return PagedModelMoneyTransferResponseFromJSONTyped(json, false);
}

export function PagedModelMoneyTransferResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelMoneyTransferResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(MoneyTransferResponseFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelMoneyTransferResponseToJSON(json: any): PagedModelMoneyTransferResponse {
    return PagedModelMoneyTransferResponseToJSONTyped(json, false);
}

export function PagedModelMoneyTransferResponseToJSONTyped(value?: PagedModelMoneyTransferResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(MoneyTransferResponseToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

