/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceTypeResponse
 */
export interface ResourceTypeResponse {
    /**
     * 
     * @type {ResourceTypeResponseResourceTypeEnum}
     * @memberof ResourceTypeResponse
     */
    resourceType: ResourceTypeResponseResourceTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum ResourceTypeResponseResourceTypeEnum {
    account = 'ACCOUNT',
    accountTransfers = 'ACCOUNT_TRANSFERS',
    accountCards = 'ACCOUNT_CARDS',
    card = 'CARD',
    cardPayments = 'CARD_PAYMENTS',
    customerBeneficiaries = 'CUSTOMER_BENEFICIARIES'
}


/**
 * Check if a given object implements the ResourceTypeResponse interface.
 */
export function instanceOfResourceTypeResponse(value: object): value is ResourceTypeResponse {
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    return true;
}

export function ResourceTypeResponseFromJSON(json: any): ResourceTypeResponse {
    return ResourceTypeResponseFromJSONTyped(json, false);
}

export function ResourceTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceTypeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceType': json['resourceType'],
    };
}

export function ResourceTypeResponseToJSON(json: any): ResourceTypeResponse {
    return ResourceTypeResponseToJSONTyped(json, false);
}

export function ResourceTypeResponseToJSONTyped(value?: ResourceTypeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resourceType': value['resourceType'],
    };
}

