/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardStatusRequest
 */
export interface CardStatusRequest {
    /**
     * 
     * @type {boolean}
     * @memberof CardStatusRequest
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the CardStatusRequest interface.
 */
export function instanceOfCardStatusRequest(value: object): value is CardStatusRequest {
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function CardStatusRequestFromJSON(json: any): CardStatusRequest {
    return CardStatusRequestFromJSONTyped(json, false);
}

export function CardStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isActive': json['isActive'],
    };
}

export function CardStatusRequestToJSON(json: any): CardStatusRequest {
    return CardStatusRequestToJSONTyped(json, false);
}

export function CardStatusRequestToJSONTyped(value?: CardStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isActive': value['isActive'],
    };
}

