/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardRequest
 */
export interface CardRequest {
    /**
     * 
     * @type {string}
     * @memberof CardRequest
     */
    iban: string;
    /**
     * 
     * @type {number}
     * @memberof CardRequest
     */
    transactionCeiling: number;
    /**
     * 
     * @type {number}
     * @memberof CardRequest
     */
    rolling30Ceiling: number;
}

/**
 * Check if a given object implements the CardRequest interface.
 */
export function instanceOfCardRequest(value: object): value is CardRequest {
    if (!('iban' in value) || value['iban'] === undefined) return false;
    if (!('transactionCeiling' in value) || value['transactionCeiling'] === undefined) return false;
    if (!('rolling30Ceiling' in value) || value['rolling30Ceiling'] === undefined) return false;
    return true;
}

export function CardRequestFromJSON(json: any): CardRequest {
    return CardRequestFromJSONTyped(json, false);
}

export function CardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iban': json['iban'],
        'transactionCeiling': json['transactionCeiling'],
        'rolling30Ceiling': json['rolling30Ceiling'],
    };
}

export function CardRequestToJSON(json: any): CardRequest {
    return CardRequestToJSONTyped(json, false);
}

export function CardRequestToJSONTyped(value?: CardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iban': value['iban'],
        'transactionCeiling': value['transactionCeiling'],
        'rolling30Ceiling': value['rolling30Ceiling'],
    };
}

