/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardPaymentCreationRequest
 */
export interface CardPaymentCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof CardPaymentCreationRequest
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof CardPaymentCreationRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof CardPaymentCreationRequest
     */
    cardNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CardPaymentCreationRequest
     */
    destinationIban: string;
}

/**
 * Check if a given object implements the CardPaymentCreationRequest interface.
 */
export function instanceOfCardPaymentCreationRequest(value: object): value is CardPaymentCreationRequest {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('destinationIban' in value) || value['destinationIban'] === undefined) return false;
    return true;
}

export function CardPaymentCreationRequestFromJSON(json: any): CardPaymentCreationRequest {
    return CardPaymentCreationRequestFromJSONTyped(json, false);
}

export function CardPaymentCreationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardPaymentCreationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'amount': json['amount'],
        'cardNumber': json['cardNumber'] == null ? undefined : json['cardNumber'],
        'destinationIban': json['destinationIban'],
    };
}

export function CardPaymentCreationRequestToJSON(json: any): CardPaymentCreationRequest {
    return CardPaymentCreationRequestToJSONTyped(json, false);
}

export function CardPaymentCreationRequestToJSONTyped(value?: CardPaymentCreationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'amount': value['amount'],
        'cardNumber': value['cardNumber'],
        'destinationIban': value['destinationIban'],
    };
}

