/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardPaymentResponse
 */
export interface CardPaymentResponse {
    /**
     * 
     * @type {number}
     * @memberof CardPaymentResponse
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof CardPaymentResponse
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof CardPaymentResponse
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof CardPaymentResponse
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof CardPaymentResponse
     */
    cardNumber: string;
    /**
     * 
     * @type {string}
     * @memberof CardPaymentResponse
     */
    destinationIban: string;
    /**
     * 
     * @type {boolean}
     * @memberof CardPaymentResponse
     */
    isAccepted?: boolean;
}

/**
 * Check if a given object implements the CardPaymentResponse interface.
 */
export function instanceOfCardPaymentResponse(value: object): value is CardPaymentResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('cardNumber' in value) || value['cardNumber'] === undefined) return false;
    if (!('destinationIban' in value) || value['destinationIban'] === undefined) return false;
    return true;
}

export function CardPaymentResponseFromJSON(json: any): CardPaymentResponse {
    return CardPaymentResponseFromJSONTyped(json, false);
}

export function CardPaymentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardPaymentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'timestamp': (new Date(json['timestamp'])),
        'currency': json['currency'],
        'amount': json['amount'],
        'cardNumber': json['cardNumber'],
        'destinationIban': json['destinationIban'],
        'isAccepted': json['isAccepted'] == null ? undefined : json['isAccepted'],
    };
}

export function CardPaymentResponseToJSON(json: any): CardPaymentResponse {
    return CardPaymentResponseToJSONTyped(json, false);
}

export function CardPaymentResponseToJSONTyped(value?: CardPaymentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'timestamp': value['timestamp'].toISOString(),
        'currency': value['currency'],
        'amount': value['amount'],
        'cardNumber': value['cardNumber'],
        'destinationIban': value['destinationIban'],
        'isAccepted': value['isAccepted'],
    };
}

