/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardCeilingsRequest
 */
export interface CardCeilingsRequest {
    /**
     * 
     * @type {number}
     * @memberof CardCeilingsRequest
     */
    transactionCeiling: number;
    /**
     * 
     * @type {number}
     * @memberof CardCeilingsRequest
     */
    rolling30Ceiling: number;
}

/**
 * Check if a given object implements the CardCeilingsRequest interface.
 */
export function instanceOfCardCeilingsRequest(value: object): value is CardCeilingsRequest {
    if (!('transactionCeiling' in value) || value['transactionCeiling'] === undefined) return false;
    if (!('rolling30Ceiling' in value) || value['rolling30Ceiling'] === undefined) return false;
    return true;
}

export function CardCeilingsRequestFromJSON(json: any): CardCeilingsRequest {
    return CardCeilingsRequestFromJSONTyped(json, false);
}

export function CardCeilingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardCeilingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionCeiling': json['transactionCeiling'],
        'rolling30Ceiling': json['rolling30Ceiling'],
    };
}

export function CardCeilingsRequestToJSON(json: any): CardCeilingsRequest {
    return CardCeilingsRequestToJSONTyped(json, false);
}

export function CardCeilingsRequestToJSONTyped(value?: CardCeilingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactionCeiling': value['transactionCeiling'],
        'rolling30Ceiling': value['rolling30Ceiling'],
    };
}

