/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationProblemDetail
 */
export interface ValidationProblemDetail {
    /**
     * 
     * @type {string}
     * @memberof ValidationProblemDetail
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationProblemDetail
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof ValidationProblemDetail
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ValidationProblemDetail
     */
    detail?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationProblemDetail
     */
    instance?: string;
    /**
     * 
     * @type {{ [key: string]: any | null; }}
     * @memberof ValidationProblemDetail
     */
    properties?: { [key: string]: any | null; };
}

/**
 * Check if a given object implements the ValidationProblemDetail interface.
 */
export function instanceOfValidationProblemDetail(value: object): value is ValidationProblemDetail {
    return true;
}

export function ValidationProblemDetailFromJSON(json: any): ValidationProblemDetail {
    return ValidationProblemDetailFromJSONTyped(json, false);
}

export function ValidationProblemDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationProblemDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'title': json['title'] == null ? undefined : json['title'],
        'status': json['status'] == null ? undefined : json['status'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'instance': json['instance'] == null ? undefined : json['instance'],
        'properties': json['properties'] == null ? undefined : json['properties'],
    };
}

export function ValidationProblemDetailToJSON(json: any): ValidationProblemDetail {
    return ValidationProblemDetailToJSONTyped(json, false);
}

export function ValidationProblemDetailToJSONTyped(value?: ValidationProblemDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
        'status': value['status'],
        'detail': value['detail'],
        'instance': value['instance'],
        'properties': value['properties'],
    };
}

