/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ProblemDetail,
    ProblemDetailFromJSON,
    ProblemDetailToJSON,
} from '../models/ProblemDetail';
import {
    type UserResponse,
    UserResponseFromJSON,
    UserResponseToJSON,
} from '../models/UserResponse';
import {
    type ValidationProblemDetail,
    ValidationProblemDetailFromJSON,
    ValidationProblemDetailToJSON,
} from '../models/ValidationProblemDetail';

/**
 * 
 */
export class GatewayApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMe without sending the request
     */
    async getMeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns information of the current user if authenticated, ANONYMOUS otherwise
     * Returns information of the current user if authenticated, ANONYMOUS otherwise
     */
    async getMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const requestOptions = await this.getMeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Returns information of the current user if authenticated, ANONYMOUS otherwise
     * Returns information of the current user if authenticated, ANONYMOUS otherwise
     */
    async getMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.getMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for logout without sending the request
     */
    async logoutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * logout
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.logoutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * logout
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.logoutRaw(initOverrides);
    }

    /**
     * Creates request options for startLoginWithGateway without sending the request
     */
    async startLoginWithGatewayRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oauth2/authorization/gateway`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Initiate an authorization code flow with the URI to follow in the response\'s Location header
     */
    async startLoginWithGatewayRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.startLoginWithGatewayRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Initiate an authorization code flow with the URI to follow in the response\'s Location header
     */
    async startLoginWithGateway(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.startLoginWithGatewayRaw(initOverrides);
    }

}
