/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CardCeilingsRequest,
    CardCeilingsRequestFromJSON,
    CardCeilingsRequestToJSON,
} from '../models/CardCeilingsRequest';
import {
    type CardPaymentCreationRequest,
    CardPaymentCreationRequestFromJSON,
    CardPaymentCreationRequestToJSON,
} from '../models/CardPaymentCreationRequest';
import {
    type CardPaymentResponse,
    CardPaymentResponseFromJSON,
    CardPaymentResponseToJSON,
} from '../models/CardPaymentResponse';
import {
    type CardRequest,
    CardRequestFromJSON,
    CardRequestToJSON,
} from '../models/CardRequest';
import {
    type CardResponse,
    CardResponseFromJSON,
    CardResponseToJSON,
} from '../models/CardResponse';
import {
    type CardStatusRequest,
    CardStatusRequestFromJSON,
    CardStatusRequestToJSON,
} from '../models/CardStatusRequest';
import {
    type ProblemDetail,
    ProblemDetailFromJSON,
    ProblemDetailToJSON,
} from '../models/ProblemDetail';
import {
    type ValidationProblemDetail,
    ValidationProblemDetailFromJSON,
    ValidationProblemDetailToJSON,
} from '../models/ValidationProblemDetail';

export interface CreateCardRequest {
    cardRequest: CardRequest;
}

export interface CreateCardPaymentRequest {
    cardNumber: string;
    cardPaymentCreationRequest: CardPaymentCreationRequest;
}

export interface GetCardRequest {
    cardNumber: string;
}

export interface ListCardPaymentsRequest {
    cardNumber: string;
    from?: Date;
    to?: Date;
}

export interface ListCardsRequest {
    iban: string;
}

export interface SetCardCeilingsRequest {
    cardNumber: string;
    cardCeilingsRequest: CardCeilingsRequest;
}

export interface SetCardStatusRequest {
    cardNumber: string;
    cardStatusRequest: CardStatusRequest;
}

/**
 * 
 */
export class CardsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createCard without sending the request
     */
    async createCardRequestOpts(requestParameters: CreateCardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['cardRequest'] == null) {
            throw new runtime.RequiredError(
                'cardRequest',
                'Required parameter "cardRequest" was null or undefined when calling createCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/cards`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CardRequestToJSON(requestParameters['cardRequest']),
        };
    }

    /**
     * Requires the `card.create` authority.
     * Requires the `card.create` authority.
     */
    async createCardRaw(requestParameters: CreateCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createCardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires the `card.create` authority.
     * Requires the `card.create` authority.
     */
    async createCard(requestParameters: CreateCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createCardRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createCardPayment without sending the request
     */
    async createCardPaymentRequestOpts(requestParameters: CreateCardPaymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['cardNumber'] == null) {
            throw new runtime.RequiredError(
                'cardNumber',
                'Required parameter "cardNumber" was null or undefined when calling createCardPayment().'
            );
        }

        if (requestParameters['cardPaymentCreationRequest'] == null) {
            throw new runtime.RequiredError(
                'cardPaymentCreationRequest',
                'Required parameter "cardPaymentCreationRequest" was null or undefined when calling createCardPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/cards/{cardNumber}/payments`;
        urlPath = urlPath.replace('{cardNumber}', encodeURIComponent(String(requestParameters['cardNumber'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CardPaymentCreationRequestToJSON(requestParameters['cardPaymentCreationRequest']),
        };
    }

    /**
     * Requires the authenticated user is the owner of the card
     * Requires the authenticated user is the owner of the card
     */
    async createCardPaymentRaw(requestParameters: CreateCardPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createCardPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires the authenticated user is the owner of the card
     * Requires the authenticated user is the owner of the card
     */
    async createCardPayment(requestParameters: CreateCardPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createCardPaymentRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getCard without sending the request
     */
    async getCardRequestOpts(requestParameters: GetCardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['cardNumber'] == null) {
            throw new runtime.RequiredError(
                'cardNumber',
                'Required parameter "cardNumber" was null or undefined when calling getCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cards/{cardNumber}`;
        urlPath = urlPath.replace('{cardNumber}', encodeURIComponent(String(requestParameters['cardNumber'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires the `card.read_any` authority or that the authenticated user is the owner of the card
     * Requires the `card.read_any` authority or that the authenticated user is the owner of the card
     */
    async getCardRaw(requestParameters: GetCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardResponse>> {
        const requestOptions = await this.getCardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardResponseFromJSON(jsonValue));
    }

    /**
     * Requires the `card.read_any` authority or that the authenticated user is the owner of the card
     * Requires the `card.read_any` authority or that the authenticated user is the owner of the card
     */
    async getCard(requestParameters: GetCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardResponse> {
        const response = await this.getCardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCardPayments without sending the request
     */
    async listCardPaymentsRequestOpts(requestParameters: ListCardPaymentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['cardNumber'] == null) {
            throw new runtime.RequiredError(
                'cardNumber',
                'Required parameter "cardNumber" was null or undefined when calling listCardPayments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cards/{cardNumber}/payments`;
        urlPath = urlPath.replace('{cardNumber}', encodeURIComponent(String(requestParameters['cardNumber'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires the `card.read_any` authority or that the authenticated user is the owner of the card
     * Requires the `card.read_any` authority or that the authenticated user is the owner of the card
     */
    async listCardPaymentsRaw(requestParameters: ListCardPaymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CardPaymentResponse>>> {
        const requestOptions = await this.listCardPaymentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CardPaymentResponseFromJSON));
    }

    /**
     * Requires the `card.read_any` authority or that the authenticated user is the owner of the card
     * Requires the `card.read_any` authority or that the authenticated user is the owner of the card
     */
    async listCardPayments(requestParameters: ListCardPaymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CardPaymentResponse>> {
        const response = await this.listCardPaymentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCards without sending the request
     */
    async listCardsRequestOpts(requestParameters: ListCardsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['iban'] == null) {
            throw new runtime.RequiredError(
                'iban',
                'Required parameter "iban" was null or undefined when calling listCards().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['iban'] != null) {
            queryParameters['iban'] = requestParameters['iban'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cards`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires the `card.read_any` authority or that the authenticated user is the owner of the  account.
     * Requires the `card.read_any` authority or that the authenticated user is the owner of the  account.
     */
    async listCardsRaw(requestParameters: ListCardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CardResponse>>> {
        const requestOptions = await this.listCardsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CardResponseFromJSON));
    }

    /**
     * Requires the `card.read_any` authority or that the authenticated user is the owner of the  account.
     * Requires the `card.read_any` authority or that the authenticated user is the owner of the  account.
     */
    async listCards(requestParameters: ListCardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CardResponse>> {
        const response = await this.listCardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setCardCeilings without sending the request
     */
    async setCardCeilingsRequestOpts(requestParameters: SetCardCeilingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['cardNumber'] == null) {
            throw new runtime.RequiredError(
                'cardNumber',
                'Required parameter "cardNumber" was null or undefined when calling setCardCeilings().'
            );
        }

        if (requestParameters['cardCeilingsRequest'] == null) {
            throw new runtime.RequiredError(
                'cardCeilingsRequest',
                'Required parameter "cardCeilingsRequest" was null or undefined when calling setCardCeilings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/cards/{cardNumber}/ceilings`;
        urlPath = urlPath.replace('{cardNumber}', encodeURIComponent(String(requestParameters['cardNumber'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CardCeilingsRequestToJSON(requestParameters['cardCeilingsRequest']),
        };
    }

    /**
     * Requires the `card.ceilings_edit` authority
     * Requires the `card.ceilings_edit` authority
     */
    async setCardCeilingsRaw(requestParameters: SetCardCeilingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.setCardCeilingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires the `card.ceilings_edit` authority
     * Requires the `card.ceilings_edit` authority
     */
    async setCardCeilings(requestParameters: SetCardCeilingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setCardCeilingsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for setCardStatus without sending the request
     */
    async setCardStatusRequestOpts(requestParameters: SetCardStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['cardNumber'] == null) {
            throw new runtime.RequiredError(
                'cardNumber',
                'Required parameter "cardNumber" was null or undefined when calling setCardStatus().'
            );
        }

        if (requestParameters['cardStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'cardStatusRequest',
                'Required parameter "cardStatusRequest" was null or undefined when calling setCardStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/cards/{cardNumber}/status`;
        urlPath = urlPath.replace('{cardNumber}', encodeURIComponent(String(requestParameters['cardNumber'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CardStatusRequestToJSON(requestParameters['cardStatusRequest']),
        };
    }

    /**
     * Requires the `card.status_edit` authority
     * Requires the `card.status_edit` authority
     */
    async setCardStatusRaw(requestParameters: SetCardStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.setCardStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires the `card.status_edit` authority
     * Requires the `card.status_edit` authority
     */
    async setCardStatus(requestParameters: SetCardStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setCardStatusRaw(requestParameters, initOverrides);
    }

}
