/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CurrencyResponse,
    CurrencyResponseFromJSON,
    CurrencyResponseToJSON,
} from '../models/CurrencyResponse';
import {
    type ProblemDetail,
    ProblemDetailFromJSON,
    ProblemDetailToJSON,
} from '../models/ProblemDetail';
import {
    type ValidationProblemDetail,
    ValidationProblemDetailFromJSON,
    ValidationProblemDetailToJSON,
} from '../models/ValidationProblemDetail';

export interface ChangeRequest {
    digits: number;
    fromIso3: string;
    toIso3: string;
}

/**
 * 
 */
export class CurrenciesApi extends runtime.BaseAPI {

    /**
     * Creates request options for change without sending the request
     */
    async changeRequestOpts(requestParameters: ChangeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['digits'] == null) {
            throw new runtime.RequiredError(
                'digits',
                'Required parameter "digits" was null or undefined when calling change().'
            );
        }

        if (requestParameters['fromIso3'] == null) {
            throw new runtime.RequiredError(
                'fromIso3',
                'Required parameter "fromIso3" was null or undefined when calling change().'
            );
        }

        if (requestParameters['toIso3'] == null) {
            throw new runtime.RequiredError(
                'toIso3',
                'Required parameter "toIso3" was null or undefined when calling change().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['digits'] != null) {
            queryParameters['digits'] = requestParameters['digits'];
        }

        if (requestParameters['fromIso3'] != null) {
            queryParameters['fromIso3'] = requestParameters['fromIso3'];
        }

        if (requestParameters['toIso3'] != null) {
            queryParameters['toIso3'] = requestParameters['toIso3'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/currencies/change`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async changeRaw(requestParameters: ChangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.changeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async change(requestParameters: ChangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.changeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSupportedCurrencies without sending the request
     */
    async listSupportedCurrenciesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/currencies`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listSupportedCurrenciesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CurrencyResponse>>> {
        const requestOptions = await this.listSupportedCurrenciesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CurrencyResponseFromJSON));
    }

    /**
     */
    async listSupportedCurrencies(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CurrencyResponse>> {
        const response = await this.listSupportedCurrenciesRaw(initOverrides);
        return await response.value();
    }

}
