/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AccountCreationRequest,
    AccountCreationRequestFromJSON,
    AccountCreationRequestToJSON,
} from '../models/AccountCreationRequest';
import {
    type AccountResponse,
    AccountResponseFromJSON,
    AccountResponseToJSON,
} from '../models/AccountResponse';
import {
    type ProblemDetail,
    ProblemDetailFromJSON,
    ProblemDetailToJSON,
} from '../models/ProblemDetail';
import {
    type ValidationProblemDetail,
    ValidationProblemDetailFromJSON,
    ValidationProblemDetailToJSON,
} from '../models/ValidationProblemDetail';

export interface CreateAccountRequest {
    accountCreationRequest: AccountCreationRequest;
}

export interface GetAccountRequest {
    iban: string;
}

export interface ListAccountsRequest {
    customerId: string;
}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createAccount without sending the request
     */
    async createAccountRequestOpts(requestParameters: CreateAccountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountCreationRequest'] == null) {
            throw new runtime.RequiredError(
                'accountCreationRequest',
                'Required parameter "accountCreationRequest" was null or undefined when calling createAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/accounts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountCreationRequestToJSON(requestParameters['accountCreationRequest']),
        };
    }

    /**
     * Requires the `account.create` authority.
     * Requires the `account.create` authority.
     */
    async createAccountRaw(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createAccountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires the `account.create` authority.
     * Requires the `account.create` authority.
     */
    async createAccount(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createAccountRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAccount without sending the request
     */
    async getAccountRequestOpts(requestParameters: GetAccountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['iban'] == null) {
            throw new runtime.RequiredError(
                'iban',
                'Required parameter "iban" was null or undefined when calling getAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/accounts/{iban}`;
        urlPath = urlPath.replace('{iban}', encodeURIComponent(String(requestParameters['iban'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires the `account.read_any` authority or that the given account\'s customer ID matches the  authenticated user.
     * Requires the `account.read_any` authority or that the given account\'s customer ID matches the  authenticated user.
     */
    async getAccountRaw(requestParameters: GetAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountResponse>> {
        const requestOptions = await this.getAccountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountResponseFromJSON(jsonValue));
    }

    /**
     * Requires the `account.read_any` authority or that the given account\'s customer ID matches the  authenticated user.
     * Requires the `account.read_any` authority or that the given account\'s customer ID matches the  authenticated user.
     */
    async getAccount(requestParameters: GetAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountResponse> {
        const response = await this.getAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAccounts without sending the request
     */
    async listAccountsRequestOpts(requestParameters: ListAccountsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling listAccounts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['customerId'] != null) {
            queryParameters['customerId'] = requestParameters['customerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/accounts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires the `account.read_any` authority or that the given customer ID matches the  authenticated user.
     * Requires the `account.read_any` authority or that the given customer ID matches the  authenticated user.
     */
    async listAccountsRaw(requestParameters: ListAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AccountResponse>>> {
        const requestOptions = await this.listAccountsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccountResponseFromJSON));
    }

    /**
     * Requires the `account.read_any` authority or that the given customer ID matches the  authenticated user.
     * Requires the `account.read_any` authority or that the given customer ID matches the  authenticated user.
     */
    async listAccounts(requestParameters: ListAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AccountResponse>> {
        const response = await this.listAccountsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
