/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ProblemDetail,
    ProblemDetailFromJSON,
    ProblemDetailToJSON,
} from '../models/ProblemDetail';
import {
    type ResourceTypeResponse,
    ResourceTypeResponseFromJSON,
    ResourceTypeResponseToJSON,
} from '../models/ResourceTypeResponse';
import {
    type ValidationProblemDetail,
    ValidationProblemDetailFromJSON,
    ValidationProblemDetailToJSON,
} from '../models/ValidationProblemDetail';

/**
 * 
 */
export class AccountServiceEventsApi extends runtime.BaseAPI {

    /**
     * Creates request options for listResourceTypes without sending the request
     */
    async listResourceTypesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/events/resource-types`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listResourceTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ResourceTypeResponse>>> {
        const requestOptions = await this.listResourceTypesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ResourceTypeResponseFromJSON));
    }

    /**
     */
    async listResourceTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ResourceTypeResponse>> {
        const response = await this.listResourceTypesRaw(initOverrides);
        return await response.value();
    }

}
