/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MoneyTransferRequest,
    MoneyTransferRequestFromJSON,
    MoneyTransferRequestToJSON,
} from '../models/MoneyTransferRequest';
import {
    type MoneyTransferResponse,
    MoneyTransferResponseFromJSON,
    MoneyTransferResponseToJSON,
} from '../models/MoneyTransferResponse';
import {
    type PagedModelMoneyTransferResponse,
    PagedModelMoneyTransferResponseFromJSON,
    PagedModelMoneyTransferResponseToJSON,
} from '../models/PagedModelMoneyTransferResponse';
import {
    type ProblemDetail,
    ProblemDetailFromJSON,
    ProblemDetailToJSON,
} from '../models/ProblemDetail';
import {
    type ValidationProblemDetail,
    ValidationProblemDetailFromJSON,
    ValidationProblemDetailToJSON,
} from '../models/ValidationProblemDetail';

export interface GetMoneyTransferRequest {
    transferId: number;
}

export interface ListMoneyTransfersRequest {
    sourceIban?: string;
    destinationIban?: string;
    minAmount?: number;
    maxAmount?: number;
    currency?: string;
    timestampAfter?: Date;
    timestampBefore?: Date;
    labelContaining?: string;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface TransferMoneyBetweenAccountsRequest {
    moneyTransferRequest: MoneyTransferRequest;
}

/**
 * 
 */
export class MoneyTransfersApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMoneyTransfer without sending the request
     */
    async getMoneyTransferRequestOpts(requestParameters: GetMoneyTransferRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['transferId'] == null) {
            throw new runtime.RequiredError(
                'transferId',
                'Required parameter "transferId" was null or undefined when calling getMoneyTransfer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/transfers/{transferId}`;
        urlPath = urlPath.replace('{transferId}', encodeURIComponent(String(requestParameters['transferId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires the `account.read_any` authority or that the authenticated user is the owner of the  source or destination account.
     * Requires the `account.read_any` authority or that the authenticated user is the owner of the  source or destination account.
     */
    async getMoneyTransferRaw(requestParameters: GetMoneyTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MoneyTransferResponse>> {
        const requestOptions = await this.getMoneyTransferRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MoneyTransferResponseFromJSON(jsonValue));
    }

    /**
     * Requires the `account.read_any` authority or that the authenticated user is the owner of the  source or destination account.
     * Requires the `account.read_any` authority or that the authenticated user is the owner of the  source or destination account.
     */
    async getMoneyTransfer(requestParameters: GetMoneyTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MoneyTransferResponse> {
        const response = await this.getMoneyTransferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMoneyTransfers without sending the request
     */
    async listMoneyTransfersRequestOpts(requestParameters: ListMoneyTransfersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['sourceIban'] != null) {
            queryParameters['sourceIban'] = requestParameters['sourceIban'];
        }

        if (requestParameters['destinationIban'] != null) {
            queryParameters['destinationIban'] = requestParameters['destinationIban'];
        }

        if (requestParameters['minAmount'] != null) {
            queryParameters['minAmount'] = requestParameters['minAmount'];
        }

        if (requestParameters['maxAmount'] != null) {
            queryParameters['maxAmount'] = requestParameters['maxAmount'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['timestampAfter'] != null) {
            queryParameters['timestampAfter'] = (requestParameters['timestampAfter'] as any).toISOString();
        }

        if (requestParameters['timestampBefore'] != null) {
            queryParameters['timestampBefore'] = (requestParameters['timestampBefore'] as any).toISOString();
        }

        if (requestParameters['labelContaining'] != null) {
            queryParameters['labelContaining'] = requestParameters['labelContaining'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/transfers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires the `account.read_any` authority or that the authenticated user is the owner of the  source or destination account.
     * Requires the `account.read_any` authority or that the authenticated user is the owner of the  source or destination account.
     */
    async listMoneyTransfersRaw(requestParameters: ListMoneyTransfersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelMoneyTransferResponse>> {
        const requestOptions = await this.listMoneyTransfersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelMoneyTransferResponseFromJSON(jsonValue));
    }

    /**
     * Requires the `account.read_any` authority or that the authenticated user is the owner of the  source or destination account.
     * Requires the `account.read_any` authority or that the authenticated user is the owner of the  source or destination account.
     */
    async listMoneyTransfers(requestParameters: ListMoneyTransfersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelMoneyTransferResponse> {
        const response = await this.listMoneyTransfersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for transferMoneyBetweenAccounts without sending the request
     */
    async transferMoneyBetweenAccountsRequestOpts(requestParameters: TransferMoneyBetweenAccountsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['moneyTransferRequest'] == null) {
            throw new runtime.RequiredError(
                'moneyTransferRequest',
                'Required parameter "moneyTransferRequest" was null or undefined when calling transferMoneyBetweenAccounts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/transfers`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MoneyTransferRequestToJSON(requestParameters['moneyTransferRequest']),
        };
    }

    /**
     * Requires the `account.transfer` authority.   This labs implementation ignores other banks. If the source or destination account isn\'t  managed by this service (another bank?), the withdraw / credit is ignored and a transfer is  saved anyway.
     * Requires the `account.transfer` authority.   This labs implementation ignores other banks. If the source or destination account isn\'t  managed by this service (another bank?), the withdraw / credit is ignored and a transfer is  saved anyway.
     */
    async transferMoneyBetweenAccountsRaw(requestParameters: TransferMoneyBetweenAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.transferMoneyBetweenAccountsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires the `account.transfer` authority.   This labs implementation ignores other banks. If the source or destination account isn\'t  managed by this service (another bank?), the withdraw / credit is ignored and a transfer is  saved anyway.
     * Requires the `account.transfer` authority.   This labs implementation ignores other banks. If the source or destination account isn\'t  managed by this service (another bank?), the withdraw / credit is ignored and a transfer is  saved anyway.
     */
    async transferMoneyBetweenAccounts(requestParameters: TransferMoneyBetweenAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transferMoneyBetweenAccountsRaw(requestParameters, initOverrides);
    }

}
