/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BeneficiaryRequest
 */
export interface BeneficiaryRequest {
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryRequest
     */
    iban: string;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryRequest
     */
    label: string;
}

/**
 * Check if a given object implements the BeneficiaryRequest interface.
 */
export function instanceOfBeneficiaryRequest(value: object): value is BeneficiaryRequest {
    if (!('iban' in value) || value['iban'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function BeneficiaryRequestFromJSON(json: any): BeneficiaryRequest {
    return BeneficiaryRequestFromJSONTyped(json, false);
}

export function BeneficiaryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeneficiaryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iban': json['iban'],
        'label': json['label'],
    };
}

export function BeneficiaryRequestToJSON(json: any): BeneficiaryRequest {
    return BeneficiaryRequestToJSONTyped(json, false);
}

export function BeneficiaryRequestToJSONTyped(value?: BeneficiaryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iban': value['iban'],
        'label': value['label'],
    };
}

