/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BeneficiaryResponse
 */
export interface BeneficiaryResponse {
    /**
     * 
     * @type {number}
     * @memberof BeneficiaryResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryResponse
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryResponse
     */
    iban: string;
}

/**
 * Check if a given object implements the BeneficiaryResponse interface.
 */
export function instanceOfBeneficiaryResponse(value: object): value is BeneficiaryResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('iban' in value) || value['iban'] === undefined) return false;
    return true;
}

export function BeneficiaryResponseFromJSON(json: any): BeneficiaryResponse {
    return BeneficiaryResponseFromJSONTyped(json, false);
}

export function BeneficiaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeneficiaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'iban': json['iban'],
    };
}

export function BeneficiaryResponseToJSON(json: any): BeneficiaryResponse {
    return BeneficiaryResponseToJSONTyped(json, false);
}

export function BeneficiaryResponseToJSONTyped(value?: BeneficiaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'iban': value['iban'],
    };
}

