/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerCreationRequest
 */
export interface CustomerCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof CustomerCreationRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerCreationRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerCreationRequest
     */
    email: string;
}

/**
 * Check if a given object implements the CustomerCreationRequest interface.
 */
export function instanceOfCustomerCreationRequest(value: object): value is CustomerCreationRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CustomerCreationRequestFromJSON(json: any): CustomerCreationRequest {
    return CustomerCreationRequestFromJSONTyped(json, false);
}

export function CustomerCreationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerCreationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
    };
}

export function CustomerCreationRequestToJSON(json: any): CustomerCreationRequest {
    return CustomerCreationRequestToJSONTyped(json, false);
}

export function CustomerCreationRequestToJSONTyped(value?: CustomerCreationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
    };
}

