/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { CustomerResponse } from './CustomerResponse';
import {
    CustomerResponseFromJSON,
    CustomerResponseFromJSONTyped,
    CustomerResponseToJSON,
    CustomerResponseToJSONTyped,
} from './CustomerResponse';

/**
 * 
 * @export
 * @interface PagedModelCustomerResponse
 */
export interface PagedModelCustomerResponse {
    /**
     * 
     * @type {Array<CustomerResponse>}
     * @memberof PagedModelCustomerResponse
     */
    content?: Array<CustomerResponse>;
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelCustomerResponse
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelCustomerResponse interface.
 */
export function instanceOfPagedModelCustomerResponse(value: object): value is PagedModelCustomerResponse {
    return true;
}

export function PagedModelCustomerResponseFromJSON(json: any): PagedModelCustomerResponse {
    return PagedModelCustomerResponseFromJSONTyped(json, false);
}

export function PagedModelCustomerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelCustomerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(CustomerResponseFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelCustomerResponseToJSON(json: any): PagedModelCustomerResponse {
    return PagedModelCustomerResponseToJSONTyped(json, false);
}

export function PagedModelCustomerResponseToJSONTyped(value?: PagedModelCustomerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(CustomerResponseToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

