/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BeneficiaryRequest,
    BeneficiaryRequestFromJSON,
    BeneficiaryRequestToJSON,
} from '../models/BeneficiaryRequest';
import {
    type BeneficiaryResponse,
    BeneficiaryResponseFromJSON,
    BeneficiaryResponseToJSON,
} from '../models/BeneficiaryResponse';
import {
    type CustomerCreationRequest,
    CustomerCreationRequestFromJSON,
    CustomerCreationRequestToJSON,
} from '../models/CustomerCreationRequest';
import {
    type CustomerResponse,
    CustomerResponseFromJSON,
    CustomerResponseToJSON,
} from '../models/CustomerResponse';
import {
    type PagedModelCustomerResponse,
    PagedModelCustomerResponseFromJSON,
    PagedModelCustomerResponseToJSON,
} from '../models/PagedModelCustomerResponse';
import {
    type ProblemDetail,
    ProblemDetailFromJSON,
    ProblemDetailToJSON,
} from '../models/ProblemDetail';
import {
    type ValidationProblemDetail,
    ValidationProblemDetailFromJSON,
    ValidationProblemDetailToJSON,
} from '../models/ValidationProblemDetail';

export interface AddBeneficiaryRequest {
    customerId: string;
    beneficiaryRequest: BeneficiaryRequest;
}

export interface CreateCustomerRequest {
    customerCreationRequest: CustomerCreationRequest;
}

export interface DeleteBeneficiaryRequest {
    customerId: string;
    beneficiaryId: number;
}

export interface GetBeneficiaryRequest {
    customerId: string;
    beneficiaryId: number;
}

export interface GetCustomerRequest {
    customerId: string;
}

export interface ListBeneficiariesRequest {
    customerId: string;
}

export interface ListCustomersRequest {
    search?: string;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface UpdateBeneficiaryRequest {
    customerId: string;
    beneficiaryId: number;
    beneficiaryRequest: BeneficiaryRequest;
}

/**
 * 
 */
export class CustomersApi extends runtime.BaseAPI {

    /**
     * Creates request options for addBeneficiary without sending the request
     */
    async addBeneficiaryRequestOpts(requestParameters: AddBeneficiaryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling addBeneficiary().'
            );
        }

        if (requestParameters['beneficiaryRequest'] == null) {
            throw new runtime.RequiredError(
                'beneficiaryRequest',
                'Required parameter "beneficiaryRequest" was null or undefined when calling addBeneficiary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/customers/{customerId}/beneficiaries`;
        urlPath = urlPath.replace('{customerId}', encodeURIComponent(String(requestParameters['customerId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BeneficiaryRequestToJSON(requestParameters['beneficiaryRequest']),
        };
    }

    /**
     * Requires the `customer.edit` authority or the user to be the customer
     * Requires the `customer.edit` authority or the user to be the customer
     */
    async addBeneficiaryRaw(requestParameters: AddBeneficiaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.addBeneficiaryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires the `customer.edit` authority or the user to be the customer
     * Requires the `customer.edit` authority or the user to be the customer
     */
    async addBeneficiary(requestParameters: AddBeneficiaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addBeneficiaryRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createCustomer without sending the request
     */
    async createCustomerRequestOpts(requestParameters: CreateCustomerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerCreationRequest'] == null) {
            throw new runtime.RequiredError(
                'customerCreationRequest',
                'Required parameter "customerCreationRequest" was null or undefined when calling createCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/customers`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerCreationRequestToJSON(requestParameters['customerCreationRequest']),
        };
    }

    /**
     * Requires the `customer.edit` authority
     * Requires the `customer.edit` authority
     */
    async createCustomerRaw(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createCustomerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Requires the `customer.edit` authority
     * Requires the `customer.edit` authority
     */
    async createCustomer(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createCustomerRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteBeneficiary without sending the request
     */
    async deleteBeneficiaryRequestOpts(requestParameters: DeleteBeneficiaryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling deleteBeneficiary().'
            );
        }

        if (requestParameters['beneficiaryId'] == null) {
            throw new runtime.RequiredError(
                'beneficiaryId',
                'Required parameter "beneficiaryId" was null or undefined when calling deleteBeneficiary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/customers/{customerId}/beneficiaries/{beneficiaryId}`;
        urlPath = urlPath.replace('{customerId}', encodeURIComponent(String(requestParameters['customerId'])));
        urlPath = urlPath.replace('{beneficiaryId}', encodeURIComponent(String(requestParameters['beneficiaryId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteBeneficiaryRaw(requestParameters: DeleteBeneficiaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteBeneficiaryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteBeneficiary(requestParameters: DeleteBeneficiaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBeneficiaryRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getBeneficiary without sending the request
     */
    async getBeneficiaryRequestOpts(requestParameters: GetBeneficiaryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling getBeneficiary().'
            );
        }

        if (requestParameters['beneficiaryId'] == null) {
            throw new runtime.RequiredError(
                'beneficiaryId',
                'Required parameter "beneficiaryId" was null or undefined when calling getBeneficiary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/customers/{customerId}/beneficiaries/{beneficiaryId}`;
        urlPath = urlPath.replace('{customerId}', encodeURIComponent(String(requestParameters['customerId'])));
        urlPath = urlPath.replace('{beneficiaryId}', encodeURIComponent(String(requestParameters['beneficiaryId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getBeneficiaryRaw(requestParameters: GetBeneficiaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BeneficiaryResponse>> {
        const requestOptions = await this.getBeneficiaryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BeneficiaryResponseFromJSON(jsonValue));
    }

    /**
     */
    async getBeneficiary(requestParameters: GetBeneficiaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BeneficiaryResponse> {
        const response = await this.getBeneficiaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCustomer without sending the request
     */
    async getCustomerRequestOpts(requestParameters: GetCustomerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling getCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/customers/{customerId}`;
        urlPath = urlPath.replace('{customerId}', encodeURIComponent(String(requestParameters['customerId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires the `customer.read_any` authority or the user to be the customer
     * Requires the `customer.read_any` authority or the user to be the customer
     */
    async getCustomerRaw(requestParameters: GetCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerResponse>> {
        const requestOptions = await this.getCustomerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerResponseFromJSON(jsonValue));
    }

    /**
     * Requires the `customer.read_any` authority or the user to be the customer
     * Requires the `customer.read_any` authority or the user to be the customer
     */
    async getCustomer(requestParameters: GetCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerResponse> {
        const response = await this.getCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listBeneficiaries without sending the request
     */
    async listBeneficiariesRequestOpts(requestParameters: ListBeneficiariesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling listBeneficiaries().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/customers/{customerId}/beneficiaries`;
        urlPath = urlPath.replace('{customerId}', encodeURIComponent(String(requestParameters['customerId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires the `customer.read_any` authority or the user to be the customer
     * Requires the `customer.read_any` authority or the user to be the customer
     */
    async listBeneficiariesRaw(requestParameters: ListBeneficiariesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BeneficiaryResponse>>> {
        const requestOptions = await this.listBeneficiariesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BeneficiaryResponseFromJSON));
    }

    /**
     * Requires the `customer.read_any` authority or the user to be the customer
     * Requires the `customer.read_any` authority or the user to be the customer
     */
    async listBeneficiaries(requestParameters: ListBeneficiariesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BeneficiaryResponse>> {
        const response = await this.listBeneficiariesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCustomers without sending the request
     */
    async listCustomersRequestOpts(requestParameters: ListCustomersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/customers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requires the `customer.read_any` authority
     * Requires the `customer.read_any` authority
     */
    async listCustomersRaw(requestParameters: ListCustomersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelCustomerResponse>> {
        const requestOptions = await this.listCustomersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelCustomerResponseFromJSON(jsonValue));
    }

    /**
     * Requires the `customer.read_any` authority
     * Requires the `customer.read_any` authority
     */
    async listCustomers(requestParameters: ListCustomersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelCustomerResponse> {
        const response = await this.listCustomersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateBeneficiary without sending the request
     */
    async updateBeneficiaryRequestOpts(requestParameters: UpdateBeneficiaryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling updateBeneficiary().'
            );
        }

        if (requestParameters['beneficiaryId'] == null) {
            throw new runtime.RequiredError(
                'beneficiaryId',
                'Required parameter "beneficiaryId" was null or undefined when calling updateBeneficiary().'
            );
        }

        if (requestParameters['beneficiaryRequest'] == null) {
            throw new runtime.RequiredError(
                'beneficiaryRequest',
                'Required parameter "beneficiaryRequest" was null or undefined when calling updateBeneficiary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/customers/{customerId}/beneficiaries/{beneficiaryId}`;
        urlPath = urlPath.replace('{customerId}', encodeURIComponent(String(requestParameters['customerId'])));
        urlPath = urlPath.replace('{beneficiaryId}', encodeURIComponent(String(requestParameters['beneficiaryId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BeneficiaryRequestToJSON(requestParameters['beneficiaryRequest']),
        };
    }

    /**
     */
    async updateBeneficiaryRaw(requestParameters: UpdateBeneficiaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateBeneficiaryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateBeneficiary(requestParameters: UpdateBeneficiaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateBeneficiaryRaw(requestParameters, initOverrides);
    }

}
