/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCardsCardNumberRouteImport } from './routes/_authenticated.cards.$cardNumber'
import { Route as AuthenticatedAccountsIbanRouteImport } from './routes/_authenticated.accounts.$iban'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCardsCardNumberRoute =
  AuthenticatedCardsCardNumberRouteImport.update({
    id: '/_authenticated/cards/$cardNumber',
    path: '/cards/$cardNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountsIbanRoute =
  AuthenticatedAccountsIbanRouteImport.update({
    id: '/_authenticated/accounts/$iban',
    path: '/accounts/$iban',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts/$iban': typeof AuthenticatedAccountsIbanRoute
  '/cards/$cardNumber': typeof AuthenticatedCardsCardNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts/$iban': typeof AuthenticatedAccountsIbanRoute
  '/cards/$cardNumber': typeof AuthenticatedCardsCardNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/accounts/$iban': typeof AuthenticatedAccountsIbanRoute
  '/_authenticated/cards/$cardNumber': typeof AuthenticatedCardsCardNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accounts/$iban' | '/cards/$cardNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accounts/$iban' | '/cards/$cardNumber'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/accounts/$iban'
    | '/_authenticated/cards/$cardNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAccountsIbanRoute: typeof AuthenticatedAccountsIbanRoute
  AuthenticatedCardsCardNumberRoute: typeof AuthenticatedCardsCardNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cards/$cardNumber': {
      id: '/_authenticated/cards/$cardNumber'
      path: '/cards/$cardNumber'
      fullPath: '/cards/$cardNumber'
      preLoaderRoute: typeof AuthenticatedCardsCardNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts/$iban': {
      id: '/_authenticated/accounts/$iban'
      path: '/accounts/$iban'
      fullPath: '/accounts/$iban'
      preLoaderRoute: typeof AuthenticatedAccountsIbanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAccountsIbanRoute: AuthenticatedAccountsIbanRoute,
  AuthenticatedCardsCardNumberRoute: AuthenticatedCardsCardNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
