/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsCardNumberRouteImport } from './routes/cards.$cardNumber'
import { Route as AccountsIbanRouteImport } from './routes/accounts.$iban'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardNumberRoute = CardsCardNumberRouteImport.update({
  id: '/cards/$cardNumber',
  path: '/cards/$cardNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIbanRoute = AccountsIbanRouteImport.update({
  id: '/accounts/$iban',
  path: '/accounts/$iban',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts/$iban': typeof AccountsIbanRoute
  '/cards/$cardNumber': typeof CardsCardNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts/$iban': typeof AccountsIbanRoute
  '/cards/$cardNumber': typeof CardsCardNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts/$iban': typeof AccountsIbanRoute
  '/cards/$cardNumber': typeof CardsCardNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accounts/$iban' | '/cards/$cardNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accounts/$iban' | '/cards/$cardNumber'
  id: '__root__' | '/' | '/accounts/$iban' | '/cards/$cardNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsIbanRoute: typeof AccountsIbanRoute
  CardsCardNumberRoute: typeof CardsCardNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardNumber': {
      id: '/cards/$cardNumber'
      path: '/cards/$cardNumber'
      fullPath: '/cards/$cardNumber'
      preLoaderRoute: typeof CardsCardNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$iban': {
      id: '/accounts/$iban'
      path: '/accounts/$iban'
      fullPath: '/accounts/$iban'
      preLoaderRoute: typeof AccountsIbanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsIbanRoute: AccountsIbanRoute,
  CardsCardNumberRoute: CardsCardNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
