/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Contract shared by every business service publishing to RabbitMQ and by the gateway relaying
 *  events to the frontend over Server-Sent Events. Payload stays minimal (identifiers only): the
 *  frontend is expected to refetch the actual resource over REST once notified.
 * 
 *  <p>
 *  <code>resourceType</code> comes from the shared {@link ResourceType ResourceType} taxonomy, so every publishing
 *  service and the frontend agree on the same resource area names. <code>resourceOwner</code> and
 *  <code>audienceRoles</code> together describe who should receive the event: the subject that owns the
 *  resource, plus whichever authorities (mirroring the service's own <code>@PreAuthorize</code>
 *  expressions) are allowed to see it regardless of ownership. The gateway only needs to know, for
 *  each connected user, their subject and granted authorities to compute the audience, it has no
 *  notion of what an "account" or a "transfer" is.
 * @export
 * @interface DomainEvent
 */
export interface DomainEvent {
    /**
     * 
     * @type {DomainEventResourceTypeEnum}
     * @memberof DomainEvent
     */
    resourceType?: DomainEventResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DomainEvent
     */
    resourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainEvent
     */
    resourceOwner?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainEvent
     */
    audienceRoles?: Array<string>;
    /**
     * 
     * @type {DomainEventEventTypeEnum}
     * @memberof DomainEvent
     */
    eventType?: DomainEventEventTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof DomainEvent
     */
    occurredAt?: Date;
}


/**
 * @export
 */
export const DomainEventResourceTypeEnum = {
    Account: 'ACCOUNT',
    AccountTransfers: 'ACCOUNT_TRANSFERS',
    AccountCards: 'ACCOUNT_CARDS',
    Card: 'CARD',
    CardPayments: 'CARD_PAYMENTS',
    CustomerBeneficiaries: 'CUSTOMER_BENEFICIARIES'
} as const;
export type DomainEventResourceTypeEnum = typeof DomainEventResourceTypeEnum[keyof typeof DomainEventResourceTypeEnum];

/**
 * @export
 */
export const DomainEventEventTypeEnum = {
    Create: 'CREATE',
    Update: 'UPDATE',
    Delete: 'DELETE'
} as const;
export type DomainEventEventTypeEnum = typeof DomainEventEventTypeEnum[keyof typeof DomainEventEventTypeEnum];


/**
 * Check if a given object implements the DomainEvent interface.
 */
export function instanceOfDomainEvent(value: object): value is DomainEvent {
    return true;
}

export function DomainEventFromJSON(json: any): DomainEvent {
    return DomainEventFromJSONTyped(json, false);
}

export function DomainEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceType': json['resourceType'] == null ? undefined : json['resourceType'],
        'resourceId': json['resourceId'] == null ? undefined : json['resourceId'],
        'resourceOwner': json['resourceOwner'] == null ? undefined : json['resourceOwner'],
        'audienceRoles': json['audienceRoles'] == null ? undefined : json['audienceRoles'],
        'eventType': json['eventType'] == null ? undefined : json['eventType'],
        'occurredAt': json['occurredAt'] == null ? undefined : (new Date(json['occurredAt'])),
    };
}

export function DomainEventToJSON(json: any): DomainEvent {
    return DomainEventToJSONTyped(json, false);
}

export function DomainEventToJSONTyped(value?: DomainEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resourceType': value['resourceType'],
        'resourceId': value['resourceId'],
        'resourceOwner': value['resourceOwner'],
        'audienceRoles': value['audienceRoles'],
        'eventType': value['eventType'],
        'occurredAt': value['occurredAt'] == null ? value['occurredAt'] : value['occurredAt'].toISOString(),
    };
}

